[platformio]
default_envs = rp2040

[env:rp2040]
platform = raspberrypi@~1.11.0
board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =
    -D RP2040
    -D SERIAL_BAUD=115200
    -O2
    -Wall
lib_deps =
    jgromes/RadioLib @ ^7.6.0
upload_protocol = picotool
monitor_speed = 115200