/**
 * @file    bench_payload.h
 * @brief   Portable bench payload generator: TX sequence header + LFSR fill.
 *
 * Payload layout (little-endian):
 *   [0..3] u32 tx sequence number (wraps at 2^32)
 *   [4..5] u16 payload length in bytes (echo of LEN=)
 *   [6.. ] xorshift32 pseudo-random fill, re-seeded from the sequence number
 *          so TX and RX sides (and the host tests) can regenerate/verify.
 */

#ifndef E80_BENCH_PAYLOAD_H
#define E80_BENCH_PAYLOAD_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define BENCH_PAYLOAD_HDR_LEN 6

/** xorshift32 step (state must not be 0). Exposed for tests. */
uint32_t bench_lfsr_next(uint32_t* state);

/** Build a bench payload for sequence number seq into buf[0..len-1].
 *  Requires len >= BENCH_PAYLOAD_HDR_LEN; len <= 511 by protocol. */
void bench_payload_build(uint8_t* buf, uint32_t len, uint32_t seq);

/** Extract the TX sequence number from a received payload (host + fw). */
uint32_t bench_payload_seq(const uint8_t* buf);

/** Extract the length field (host + fw). */
uint16_t bench_payload_len_field(const uint8_t* buf);

/** Verify the LFSR fill of a received payload. Requires len >= 8.
 *  @return true when every generated byte after the header matches. */
int bench_payload_verify(const uint8_t* buf, uint32_t len);

#ifdef __cplusplus
}
#endif

#endif /* E80_BENCH_PAYLOAD_H */
