#!/usr/bin/env python3
"""
inject_build_id.py — PlatformIO extra_script for firmware self-identification.

Supersedes tools/inject_git_version.py for the multi-radio sweep environments
(``rp2040-sweep-gps-tx``, ``rp2040-sweep-rx``).  Wires three concerns into a
single build step:

  1. Reads ``firmware/BUILD_COUNTER.txt`` and assigns the current value as
     ``FW_BUILD_ID`` (a small integer, 1-255) to the build.  The counter is
     then incremented and written back so every binary gets a unique ID.
  2. Reads the git short hash and exposes it both as a printable string
     (``FW_GIT_HASH``) and a hex integer (``FW_GIT_HASH_HEX``).
  3. Appends a row to ``firmware/BUILD_MAP.md`` so the build registry is
     always up to date.

The following compile-time macros are injected:

    FW_BUILD_ID        — int     (e.g. 42)
    FW_GIT_HASH        — string  (e.g. "abc123d")
    FW_GIT_HASH_HEX    — int     (e.g. 0xABC123D)  — for byte embedding
    FW_BINARY_NAME     — string  (e.g. "sweep-gps-tx")
    FW_BUILD_TAG       — string  (e.g. "TX0")
    FW_BUILD_TIME      — string  (ISO 8601 UTC)

All macros have fallback #defines in the firmware sources so the code still
compiles without this script (build_id falls back to 0).
"""

from __future__ import annotations

import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


# ── Paths ────────────────────────────────────────────────────────────────────
# This script lives at firmware/rp2040/scripts/inject_build_id.py
try:
    SCRIPT_DIR = Path(__file__).resolve().parent
except NameError:
    import sys, os
    SCRIPT_DIR = Path(os.path.dirname(os.path.abspath(sys.argv[0]))).resolve()
RP2040_DIR = SCRIPT_DIR.parent                   # firmware/rp2040/
FIRMWARE_DIR = RP2040_DIR.parent                 # firmware/
COUNTER_FILE = FIRMWARE_DIR / "BUILD_COUNTER.txt"
BUILD_MAP_FILE = FIRMWARE_DIR / "BUILD_MAP.md"


# ── Helpers ──────────────────────────────────────────────────────────────────
def _git_output(args, fallback="unknown"):
    """Run a git command, return stripped stdout or fallback on failure."""
    try:
        result = subprocess.run(
            args,
            stdout=subprocess.PIPE,
            text=True,
            timeout=5,
            stderr=subprocess.DEVNULL,
        )
        if result.returncode == 0:
            val = result.stdout.strip()
            if val:
                return val
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        pass
    return fallback


def _read_counter() -> int:
    """Read the build counter. Returns 1 if the file is missing/corrupt."""
    try:
        text = COUNTER_FILE.read_text().strip()
        n = int(text)
        if n < 1:
            n = 1
        return n
    except (OSError, ValueError):
        return 1


def _write_counter(n: int) -> None:
    """Write the next build counter value (n + 1)."""
    try:
        COUNTER_FILE.write_text(f"{n + 1}\n")
    except OSError as exc:
        print(f"  inject_build_id: WARN could not update counter: {exc}",
              file=sys.stderr)


def _append_build_map(build_id: int, git_hash: str, binary_name: str,
                      when: datetime) -> None:
    """Append a row to BUILD_MAP.md (creating the header if needed)."""
    date_str = when.strftime("%Y-%m-%d")
    row = (f"| {build_id:<8} | {git_hash:<10} | "
           f"{binary_name:<13} | {date_str:<19} |\n")
    try:
        # If the file is missing or doesn't yet contain the header table,
        # write a fresh copy with the header before appending.
        header = (
            "# Firmware Build Map\n\n"
            "Auto-generated by `firmware/rp2040/scripts/inject_build_id.py`.\n"
            "Each row records one PlatformIO build with a unique, "
            "auto-incremented `FW_BUILD_ID`.\n\n"
            "| build_id | git_commit | binary_name   | date                |\n"
            "|----------|------------|---------------|---------------------|\n"
        )
        if not BUILD_MAP_FILE.exists():
            BUILD_MAP_FILE.write_text(header + row)
            return
        existing = BUILD_MAP_FILE.read_text()
        if "|----" not in existing:
            BUILD_MAP_FILE.write_text(header + row)
            return
        with BUILD_MAP_FILE.open("a") as fh:
            fh.write(row)
    except OSError as exc:
        print(f"  inject_build_id: WARN could not update build map: {exc}",
              file=sys.stderr)


def _derive_binary_name(pioenv: str) -> str:
    """Derive 'sweep-gps-tx' / 'sweep-rx' from the PIO environment name."""
    name = pioenv
    for prefix in ("rp2040-", "rp2350-", "esp32-"):
        if name.startswith(prefix):
            name = name[len(prefix):]
            break
    return name or "unknown"


def _derive_build_tag(pioenv: str) -> str:
    """Derive TX0/RX0 from the PIO environment name."""
    env_lower = pioenv.lower()
    if "tx" in env_lower:
        return "TX0"
    if "rx" in env_lower:
        return "RX0"
    return "UNK0"


# ── Main ────────────────────────────────────────────────────────────────────
def main():
    try:
        Import("env")  # noqa: F821 — provided by SCons/PlatformIO
    except Exception:  # pragma: no cover — running outside PlatformIO
        print("  inject_build_id: not running under PlatformIO, skipping.")
        return

    pioenv = str(env.get("PIOENV", ""))  # noqa: F821
    if not pioenv:
        for i, arg in enumerate(sys.argv):
            if arg in ("-e", "--environment") and i + 1 < len(sys.argv):
                pioenv = sys.argv[i + 1]
                break

    # Git state
    git_hash = _git_output(
        ["git", "rev-parse", "--short=7", "HEAD"], fallback="0000000"
    )
    git_hash = git_hash[:7].ljust(7, "0")
    try:
        git_hash_hex = int(git_hash, 16)
    except ValueError:
        git_hash_hex = 0

    # Build counter (assigns this build's ID, then increments for next time)
    build_id = _read_counter()
    if build_id > 255:
        # uint8 overflow — wrap back to 1 to stay within a single packet byte
        build_id = 1
    _write_counter(build_id)

    binary_name = _derive_binary_name(pioenv)
    build_tag = _derive_build_tag(pioenv)
    build_time = datetime.now(timezone.utc)

    # Update the build registry
    _append_build_map(build_id, git_hash, binary_name, build_time)
    build_time_str = build_time.strftime("%Y-%m-%dT%H:%MZ")

    # Inject BUILD_FLAGS — string macros need escaped quotes for the compiler
    env.Append(  # noqa: F821
        BUILD_FLAGS=[
            f"-DFW_BUILD_ID={build_id}",
            f"-DFW_GIT_HASH=\\\"{git_hash}\\\"",
            f"-DFW_GIT_HASH_HEX=0x{git_hash.upper()}",
            f"-DFW_BINARY_NAME=\\\"{binary_name}\\\"",
            f"-DFW_BUILD_TAG=\\\"{build_tag}\\\"",
            f"-DFW_BUILD_TIME=\\\"{build_time_str}\\\"",
        ]
    )

    print(f"  inject_build_id: build_id={build_id} git={git_hash} "
          f"bin={binary_name} tag={build_tag} time={build_time_str}")


main()
