#!/usr/bin/env python3
"""Emit `docs/3d-model-coverage-hub.md` - the HONEST 3D coverage statement.

WHY THIS EXISTS
---------------
A render of `hub_board_v9.kicad_pcb` was produced and it was misleading: all 32
model references pointed at `${KICAD9_3DMODEL_DIR}/...`, the KiCad 3D package is
not installed, and **0 of them resolved** - so a vision model reported components
that were only silkscreen text.  A render is only evidence if you can say, for
every footprint, whether a model was actually drawn and where its dimensions came
from.  This report says exactly that, one row per footprint, and it is regenerated
from the committed board so it cannot go stale silently.

    python3 scripts/3d_model_coverage_report.py            # write the doc
    python3 scripts/3d_model_coverage_report.py --check    # exit 1 if it is stale
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
BOARD = os.path.join(REPO, "tracker", "hardware", "hub_board_v9.kicad_pcb")
INDEX = os.path.join(REPO, "tracker", "hardware", "footprints", "3dmodels", "MODEL-INDEX.json")
DOC = os.path.join(REPO, "docs", "3d-model-coverage-hub.md")
MODELS_DIR_REL = "tracker/hardware/footprints/3dmodels/"


def s_expr_blocks(text, keyword):
    out, i, tok = [], 0, "(" + keyword
    while True:
        s = text.find(tok, i)
        if s < 0:
            break
        nxt = text[s + len(tok):s + len(tok) + 1]
        if nxt and (nxt.isalnum() or nxt == "_"):
            i = s + 1
            continue
        depth, j = 0, s
        while j < len(text):
            c = text[j]
            if c == '"':
                j += 1
                while j < len(text) and text[j] != '"':
                    if text[j] == "\\":
                        j += 1
                    j += 1
            elif c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        out.append(text[s:j + 1])
        i = j + 1
    return out


def prop(block, name):
    m = re.search(r'\(property "%s" "([^"]*)"' % re.escape(name), block)
    return m.group(1) if m else ""


def parse(board_path):
    text = open(board_path, encoding="utf-8", errors="replace").read()
    rows = []
    for blk in s_expr_blocks(text, "footprint "):
        lib = re.match(r'\(footprint "([^"]+)"', blk).group(1)
        ref = prop(blk, "Reference")
        val = prop(blk, "Value")
        dnps = re.findall(r"\(dnp (yes|no)\)", blk)
        dnp = "yes" if (dnps and dnps[0] == "yes") else "no"
        models = re.findall(r'\(model "([^"]+)"', blk)
        rows.append(dict(ref=ref, value=val, lib=lib, dnp=dnp, models=models))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    rows = parse(BOARD)
    idx = json.load(open(INDEX, encoding="utf-8"))["models"]
    by_file = {}
    for name, meta in idx.items():
        by_file[meta["file"]] = (name, meta)

    counts = {"repo-local": 0, "library": 0, "none": 0}
    table = []
    model_less = []
    unsourced = []
    for r in sorted(rows, key=lambda r: r["ref"]):
        state, src, files = "NO MODEL", "-", []
        if r["models"]:
            f = r["models"][0]
            if "3dmodels/" in f:
                state = "repo-local"
            elif "${KICAD" in f:
                state = "library"
            files = [os.path.basename(x) for x in r["models"]]
            base = os.path.basename(f)
            if base in by_file:
                name, meta = by_file[base]
                src = "%s x %s x %s mm" % (meta["body_mm"][0], meta["body_mm"][1], meta["height_mm"])
                if meta["todo_unverified"]:
                    src += " **TODO(unverified)**: " + "; ".join(meta["todo_unverified"])
                    unsourced.append((name, meta["todo_unverified"]))
            else:
                src = "KiCad library model (not committed here)"
        if state == "none" or state == "NO MODEL":
            counts["none"] += 1
            model_less.append(r["ref"])
        else:
            counts[state] += 1
        table.append((r, state, src, files))

    n_fp = len(rows)
    n_ref = sum(1 for r in rows if r["models"])
    out = []
    out.append("# 3D model coverage - `hub_board_v9.kicad_pcb` (v9 hub)\n")
    out.append("> GENERATED BY `scripts/3d_model_coverage_report.py` - do not hand-edit.")
    out.append("> Regenerate with `python3 scripts/3d_model_coverage_report.py`; ")
    out.append("> `--check` exits 1 if this file is stale.\n")
    out.append("## 1. Why this document exists\n")
    out.append("A render of this board was produced and it was **misleading**.  Every one of the "
               "32 model references pointed at `${KICAD9_3DMODEL_DIR}/<lib>.3dshapes/<part>.step`. "
               "The KiCad 3D package (`kicad-packages3d`, 4.77 GB) is **not installed on the build "
               "host** and that variable is **unset**, so **0 of 32 references resolved**.  A vision "
               "model then reported components that were only silkscreen text - a confabulation "
               "caused by an empty render, not by a bad model.\n")
    out.append("Installing the 4.77 GB package is **not** the fix: this host has ~3.8 GB free, and "
               "no library contains this project's custom parts (the F33 module, the castellated "
               "LoRa2021, the SX1280 land, the wing socket, the bare solar cells).  The models are "
               "instead **generated parametrically and committed**, by "
               "`scripts/gen_3d_models.py`, which also records each dimension's provenance and "
               "flags every unsourced dimension `TODO(unverified)` **inside the model file**."
               "\n")
    out.append("## 2. What the empty area on the board is\n")
    out.append("`PVA1` and `PVA2` are real **netlist** components (`SolarCell_78x39mm`) whose "
               "Footprint field is empty, so the board builder reported them UNPLACEABLE.  The large "
               "empty rectangle on the board is therefore the **ARRAY SITE, unbuilt** - not a render "
               "artifact.  The only \"solar\" strings on the board were the wing-interface NET names "
               "(`W1..W4_SOLAR_*`).  They are now added as **DNP** footprints (the repo's existing "
               "convention: `R_NTC1`/`TH_NTC1`) so the array is visible and correctly sized.\n")
    out.append("## 3. Coverage table\n")
    out.append("| reference | value | 3D model | model file | dimensions and their source |")
    out.append("|---|---|---|---|---|")
    for r, state, src, files in table:
        dnptag = " **(DNP)**" if r["dnp"] == "yes" else ""
        f = ", ".join(files) if files else "-"
        out.append("| `%s`%s | %s | **%s** | %s | %s |" %
                   (r["ref"], dnptag, r["value"].replace("|", "/"), state, f, src))
    out.append("")
    out.append("## 4. Coverage counts\n")
    out.append("| state | footprints |")
    out.append("|---|---|")
    out.append("| `modeled (repo-local, committed)` | %d |" % counts["repo-local"])
    out.append("| `modeled (library)` | %d |" % counts["library"])
    out.append("| `NO MODEL` | %d |" % counts["none"])
    out.append("| **total** | **%d** |" % n_fp)
    out.append("")
    out.append("Of %d footprints, **%d carry a 3D model that resolves on this host** "
               "(all repo-local and committed) and **%d do not**%s.\n" %
               (n_fp, counts["repo-local"] + counts["library"], counts["none"],
                (": " + ", ".join("`%s`" % m for m in model_less)) if model_less else ""))
    out.append("## 5. Unsourced dimensions (`TODO(unverified)`)\n")
    out.append("These dimensions are **display values only** - they are NOT claims, and every one "
               "is flagged as `TODO(unverified)` in the model header itself.  A render made from "
               "them shows a correctly SIZED part with an unsourced THICKNESS unless stated.\n")
    out.append("| model | TODO(unverified) |")
    out.append("|---|---|")
    for name, todos in unsourced:
        out.append("| `%s` | %s |" % (name, "; ".join(todos)))
    out.append("")
    out.append("Fully sourced models (no `TODO(unverified)`): " +
               ", ".join("`%s`" % n for n in sorted(idx)
                         if not idx[n]["todo_unverified"]) + ".\n")
    out.append("## 6. Reproduce\n")
    out.append("```sh")
    out.append("python3 scripts/gen_3d_models.py            # regenerate the committed models")
    out.append("python3 scripts/gen_3d_models.py --check    # fail if any model drifts")
    out.append("/usr/bin/python3.14 tracker/hardware/build_hub_board_v9.py --publish   # rebuild the board")
    out.append("python3 scripts/3d_model_coverage_report.py  # regenerate this document")
    out.append("kicad-cli pcb render --output out.png --side top --quality high \\")
    out.append("    --perspective --width 1800 --height 1400 tracker/hardware/hub_board_v9.kicad_pcb")
    out.append("```")
    out.append("")
    out.append("> A machine that HAS the KiCad 3D package can restore the library models: every "
               "repo-local model's original `${KICAD*_3DMODEL_DIR}` path is recorded in "
               "`tracker/hardware/footprints/3dmodels/MODEL-INDEX.json`.\n")
    text = "\n".join(out) + "\n"

    if a.check:
        old = open(DOC, encoding="utf-8").read() if os.path.exists(DOC) else None
        if old != text:
            print("STALE: %s differs from a fresh generation" % os.path.relpath(DOC, REPO))
            return 1
        print("coverage report: up to date")
        return 0
    with open(DOC, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s  (repo-local %d / library %d / none %d of %d)" %
          (os.path.relpath(DOC, REPO), counts["repo-local"], counts["library"],
           counts["none"], n_fp))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
