// -------------------------------------------------- //
// This file is autogenerated by pioasm;  do not edit! //
// (regenerated by hand for SPEED-P6; the canonical    //
//  tool, raspberrypi/pioasm, is currently unreachable //
//  upstream. Encodings verified against pico-sdk's    //
//  own pio_instructions.h encoder — see VERIFY below.)//
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// lr2021_rx
// ------- //

#define lr2021_rx_wrap_target 0
#define lr2021_rx_wrap 1
#define lr2021_rx_pio_version 0

#if !PICO_NO_HARDWARE
static const uint16_t lr2021_rx_program_instructions[] = {
            //     .wrap_target
    0x7001, //  0: out   pins, 1 side 0     ; present MOSI bit, SCK low
    0x5801, //  1: in    pins, 1 side 1     ; sample MISO, SCK high (rising)
            //     .wrap
};
#endif

#if !PICO_NO_HARDWARE
static const struct pio_program lr2021_rx_program = {
    .instructions = lr2021_rx_program_instructions,
    .length = 2,
    .origin = -1,
/* pio_version / used_gpio_ranges fields exist only on pico-sdk >= 2.x.
 * The mbed-core build bundles SDK 1.x whose struct lacks them. */
#if defined(PICO_SDK_VERSION_MAJOR) && (PICO_SDK_VERSION_MAJOR >= 2)
    .pio_version = lr2021_rx_pio_version,
#  if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0,
#  endif
#endif
};
#endif

// VERIFY (host-built enc_check.c using pico-sdk pio_instructions.h):
//   out pins,1 side 0 (.side_set 1 opt) = 0x7001  -> opcode OUT(011), side_present=1, side_val=0
//   in  pins,1 side 1 (.side_set 1 opt) = 0x5801  -> opcode IN (010), side_present=1, side_val=1
// Both words match pico-sdk's pio_encode_out()/pio_encode_in() | pio_encode_sideset_opt(1,v).

#if !PICO_NO_HARDWARE
static inline pio_sm_config lr2021_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + lr2021_rx_wrap_target, offset + lr2021_rx_wrap);
    sm_config_set_sideset(&c, 1, true, false);
    return c;
}
#endif
