#!/usr/bin/env python3
"""
payload_sweep_config.py — Generate payload sweep configuration headers.

Generates a C header file (payload_configs.h) with #define constants for each
payload size to test. This allows the RP2040 firmware to iterate over payload
sizes at compile time or runtime.

Usage
-----
    # Default sizes: 32, 64, 128, 255
    python3 payload_sweep_config.py

    # Custom sizes
    python3 payload_sweep_config.py --sizes 16,32,64,128,255

    # Custom output path
    python3 payload_sweep_config.py --output firmware/rp2040/src/my_configs.h

    # Also generate platformio.ini environments for each size
    python3 payload_sweep_config.py --generate-pio

Output
------
    firmware/rp2040/src/payload_configs.h (default):

        // Auto-generated by payload_sweep_config.py
        // Generated: 2026-07-30T12:00:00Z
        // Sizes: 32, 64, 128, 255
        #ifndef PAYLOAD_CONFIGS_H
        #define PAYLOAD_CONFIGS_H

        #include <stdint.h>

        #define PAYLOAD_SIZE_32     32
        #define PAYLOAD_SIZE_64     64
        #define PAYLOAD_SIZE_128    128
        #define PAYLOAD_SIZE_255    255

        #define NUM_PAYLOAD_SIZES   4
        static const uint16_t payload_sizes[NUM_PAYLOAD_SIZES] = { 32, 64, 128, 255 };

        #endif // PAYLOAD_CONFIGS_H

Note: This is optional. The firmware worker may handle payload configs in
platformio.ini instead. Use --generate-pio for the PlatformIO approach.
"""
from __future__ import annotations

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


DEFAULT_SIZES = [32, 64, 128, 255]
DEFAULT_OUTPUT = "firmware/rp2040/src/payload_configs.h"


def generate_header(sizes: list[int], output_path: Path) -> Path:
    """Generate a C header file with #define constants for each payload size.

    Args:
        sizes: List of payload sizes in bytes.
        output_path: Path to write the header file.

    Returns:
        The path to the written file.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    sizes_str = ", ".join(str(s) for s in sizes)

    lines = [
        "/*",
        " * payload_configs.h — Auto-generated payload size sweep configuration.",
        " *",
        f" * Generated by payload_sweep_config.py on {timestamp}",
        f" * Payload sizes: {sizes_str}",
        " *",
        " * This file is auto-generated. Do not edit manually.",
        " * Regenerate with: python3 tools/payload_sweep_config.py",
        " */",
        "",
        "#ifndef PAYLOAD_CONFIGS_H",
        "#define PAYLOAD_CONFIGS_H",
        "",
        "#include <stdint.h>",
        "",
    ]

    # #define for each size
    lines.append("// ── Individual payload size defines ──────────────────────")
    for size in sizes:
        macro_name = f"PAYLOAD_SIZE_{size}"
        lines.append(f"#define {macro_name:<20s} {size}")
    lines.append("")

    # Array of all sizes for iteration
    lines.append("// ── Array of all payload sizes for runtime iteration ─────")
    lines.append(f"#define NUM_PAYLOAD_SIZES   {len(sizes)}")
    array_items = ", ".join(f"{s}" for s in sizes)
    lines.append(
        f"static const uint16_t payload_sizes[NUM_PAYLOAD_SIZES] = {{ {array_items} }};"
    )
    lines.append("")

    # Helper macro for max payload size
    max_size = max(sizes)
    lines.append(f"// ── Maximum payload size (for buffer allocation) ─────────")
    lines.append(f"#define PAYLOAD_SIZE_MAX    {max_size}")
    lines.append("")

    lines.append("#endif // PAYLOAD_CONFIGS_H")
    lines.append("")

    content = "\n".join(lines)

    # Create parent directories
    output_path.parent.mkdir(parents=True, exist_ok=True)

    output_path.write_text(content)
    return output_path


def generate_pio_envs(sizes: list[int], output_path: Path) -> Path:
    """Generate PlatformIO environment entries for each payload size.

    Produces a snippet suitable for appending to platformio.ini:

        [env:rp2040-payload-32]
        extends = env:rp2040-range-tx-auto
        build_flags = ${env:rp2040-range-tx-auto.build_flags} -D FLRC_PKT_SIZE=32

    Args:
        sizes: List of payload sizes in bytes.
        output_path: Path to write the .ini snippet.

    Returns:
        The path to the written file.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        f"; ── Payload sweep environments (auto-generated {timestamp}) ──",
        f"; Generated by payload_sweep_config.py",
        f"; Sizes: {', '.join(str(s) for s in sizes)}",
        "",
    ]

    for size in sizes:
        env_name = f"rp2040-payload-{size}"
        lines.append(f"[env:{env_name}]")
        lines.append(f"extends = env:rp2040-range-tx-auto")
        lines.append(
            f"build_flags = "
            f"${{env:rp2040-range-tx-auto.build_flags}} "
            f"-D FLRC_PKT_SIZE={size}"
        )
        lines.append("")

    # Also generate matching RX environments
    for size in sizes:
        env_name = f"rp2040-payload-rx-{size}"
        lines.append(f"[env:{env_name}]")
        lines.append(f"extends = env:rp2040-range-rx-auto")
        lines.append(
            f"build_flags = "
            f"${{env:rp2040-range-rx-auto.build_flags}} "
            f"-D FLRC_PKT_SIZE={size}"
        )
        lines.append("")

    content = "\n".join(lines)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)
    return output_path


def parse_sizes(s: str) -> list[int]:
    """Parse a comma-separated list of payload sizes."""
    try:
        sizes = [int(x.strip()) for x in s.split(",") if x.strip()]
    except ValueError:
        raise argparse.ArgumentTypeError(
            f"Invalid sizes: '{s}'. Use comma-separated integers."
        )
    if not sizes:
        raise argparse.ArgumentTypeError("At least one size is required.")
    for size in sizes:
        if size < 1 or size > 255:
            raise argparse.ArgumentTypeError(
                f"Payload size {size} out of range (1-255 bytes for FLRC)."
            )
    return sizes


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate payload sweep configuration headers for RP2040 firmware.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  # Default sizes (32, 64, 128, 255):\n"
            "  payload_sweep_config.py\n\n"
            "  # Custom sizes:\n"
            "  payload_sweep_config.py --sizes 16,32,64,128,255\n\n"
            "  # Generate platformio.ini environments instead:\n"
            "  payload_sweep_config.py --generate-pio\n\n"
            "  # Custom output path:\n"
            "  payload_sweep_config.py --output firmware/rp2040/src/my_configs.h\n"
        ),
    )
    parser.add_argument(
        "--sizes", type=parse_sizes, default=None,
        help=f"Comma-separated payload sizes in bytes (default: "
             f"{','.join(str(s) for s in DEFAULT_SIZES)}).",
    )
    parser.add_argument(
        "--output", "-o", default=DEFAULT_OUTPUT,
        help=f"Output header file path (default: {DEFAULT_OUTPUT}).",
    )
    parser.add_argument(
        "--generate-pio", action="store_true",
        help="Also generate platformio.ini environment entries for each size.",
    )
    parser.add_argument(
        "--pio-output", default=None,
        help="Output path for platformio.ini snippet (default: alongside header, "
             "with .pio extension).",
    )
    args = parser.parse_args()

    sizes = args.sizes if args.sizes is not None else DEFAULT_SIZES
    sizes.sort()

    output_path = Path(args.output)

    # ── Generate header ──────────────────────────────────────────────
    print(f"Generating payload config header...", flush=True)
    print(f"  Sizes : {', '.join(str(s) for s in sizes)}", flush=True)
    print(f"  Output: {output_path}", flush=True)

    written = generate_header(sizes, output_path)
    print(f"  ✓ Written: {written} ({written.stat().st_size} bytes)", flush=True)

    # ── Optionally generate platformio.ini environments ──────────────
    if args.generate_pio:
        pio_output = Path(args.pio_output) if args.pio_output else output_path.with_suffix(".pio")
        print(f"\nGenerating PlatformIO environments...", flush=True)
        print(f"  Output: {pio_output}", flush=True)
        pio_written = generate_pio_envs(sizes, pio_output)
        print(f"  ✓ Written: {pio_written} ({pio_written.stat().st_size} bytes)", flush=True)
        print(
            f"\nTo use: append the contents of {pio_written} to your platformio.ini",
            flush=True,
        )

    print(f"\nDone. {len(sizes)} payload sizes configured.", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
