#!/usr/bin/env bash
# setup-pico-udev.sh — Generate udev rules for stable RP2040 Pico device paths
#
# Scans connected RP2040 boards and creates udev symlinks like:
#   /dev/pico-<serial>    — application mode (CDC serial)
#   /dev/pico-<serial>-boot — BOOTSEL mode (mass storage)
#
# This eliminates the "paths drift on USB reconnect" problem where boards
# show up as ttyACM0/1/2/3 in unpredictable order.
#
# Usage:
#   ./setup-pico-udev.sh                    # Auto-detect all connected Picos
#   ./setup-pico-udev.sh E0C9125B0D9B tx    # Assign role "tx" to a serial
#   ./setup-pico-udev.sh E0C9125B0D9B rx    # Assign role "rx" to a serial
#
# After running, reload udev:
#   sudo udevadm control --reload-rules && sudo udevadm trigger
#
# Referenced by: balloon kanban task t_9b6720c6 (throughput validation)

set -euo pipefail

RULES_FILE="/etc/udev/rules.d/99-rp2040-pico.rules"
KNOWN_SERIALS_FILE="$HOME/.local/state/balloon/pico-serials.json"

mkdir -p "$(dirname "$KNOWN_SERIALS_FILE")"

# --- Detect connected RP2040 boards ---
detect_picos() {
    # RP2040 in application mode: VID 2e8a PID 000a (CDC ACM)
    # RP2040 in BOOTSEL mode:     VID 2e8a PID 0003 (mass storage)
    local found=0

    echo "Scanning for RP2040 boards..."

    # Check all ttyACM devices for RP2040 VID
    for dev in /dev/ttyACM*; do
        [ -e "$dev" ] || continue
        local syspath
        syspath=$(udevadm info -q property -n "$dev" 2>/dev/null | grep '^ID_USB_VENDOR_ID=' | cut -d= -f2)
        if [ "$syspath" = "2e8a" ]; then
            local serial
            serial=$(udevadm info -q property -n "$dev" 2>/dev/null | grep '^ID_SERIAL_SHORT=' | cut -d= -f2)
            local model
            model=$(udevadm info -q property -n "$dev" 2>/dev/null | grep '^ID_MODEL=' | cut -d= -f2)
            echo "  FOUND: $dev serial=$serial model=$model"
            echo "$serial"
            found=1
        fi
    done

    # Also check BOOTSEL mode (PID 0003, shows as mass storage not ttyACM)
    for dev in /dev/sd*; do
        [ -e "$dev" ] || continue
        local vid
        vid=$(udevadm info -q property -n "$dev" 2>/dev/null | grep '^ID_USB_VENDOR_ID=' | cut -d= -f2)
        if [ "$vid" = "2e8a" ]; then
            local serial
            serial=$(udevadm info -q property -n "$dev" 2>/dev/null | grep '^ID_SERIAL_SHORT=' | cut -d= -f2)
            echo "  FOUND (BOOTSEL): $dev serial=$serial"
            echo "$serial"
            found=1
        fi
    done

    if [ "$found" -eq 0 ]; then
        echo "  No RP2040 boards found."
    fi
}

# --- Generate udev rules ---
generate_rules() {
    echo "# RP2040 Pico stable device symlinks" > /tmp/pico-udev-rules.tmp
    echo "# Generated by setup-pico-udev.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> /tmp/pico-udev-rules.tmp
    echo "# Reload after changes: sudo udevadm control --reload-rules && sudo udevadm trigger" >> /tmp/pico-udev-rules.tmp
    echo "" >> /tmp/pico-udev-rules.tmp

    if [ -f "$KNOWN_SERIALS_FILE" ]; then
        # Read known serials and generate symlinks
        local role tx_serial rx_serial
        tx_serial=$(python3 -c "import json; d=json.load(open('$KNOWN_SERIALS_FILE')); print(d.get('tx',''))" 2>/dev/null || echo "")
        rx_serial=$(python3 -c "import json; d=json.load(open('$KNOWN_SERIALS_FILE')); print(d.get('rx',''))" 2>/dev/null || echo "")

        if [ -n "$tx_serial" ]; then
            echo "# TX board (serial $tx_serial)" >> /tmp/pico-udev-rules.tmp
            echo "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"2e8a\", ATTRS{serial}==\"$tx_serial\", SYMLINK+=\"pico-tx\"" >> /tmp/pico-udev-rules.tmp
            echo "SUBSYSTEM==\"block\", ATTRS{idVendor}==\"2e8a\", ATTRS{serial}==\"$tx_serial\", SYMLINK+=\"pico-tx-boot\"" >> /tmp/pico-udev-rules.tmp
            echo "" >> /tmp/pico-udev-rules.tmp
        fi

        if [ -n "$rx_serial" ]; then
            echo "# RX board (serial $rx_serial)" >> /tmp/pico-udev-rules.tmp
            echo "SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"2e8a\", ATTRS{serial}==\"$rx_serial\", SYMLINK+=\"pico-rx\"" >> /tmp/pico-udev-rules.tmp
            echo "SUBSYSTEM==\"block\", ATTRS{idVendor}==\"2e8a\", ATTRS{serial}==\"$rx_serial\", SYMLINK+=\"pico-rx-boot\"" >> /tmp/pico-udev-rules.tmp
            echo "" >> /tmp/pico-udev-rules.tmp
        fi

        echo "Rules generated for TX=$tx_serial RX=$rx_serial"
        echo "Install: sudo cp /tmp/pico-udev-rules.tmp $RULES_FILE"
        echo "Reload:  sudo udevadm control --reload-rules && sudo udevadm trigger"
    else
        echo "No known serials. Run with a serial+role argument to register boards."
        echo "Example: $0 E0C9125B0D9B tx"
    fi
}

# --- Register a serial with a role ---
register_serial() {
    local serial="$1"
    local role="$2"

    python3 -c "
import json, os
f = '$KNOWN_SERIALS_FILE'
d = {}
if os.path.exists(f):
    try:
        d = json.load(open(f))
    except:
        pass
d['$role'] = '$serial'
# Also store a list of all known serials
serials = set(d.get('all_serials', []))
serials.add('$serial')
d['all_serials'] = sorted(serials)
json.dump(d, open(f, 'w'), indent=2)
print(f'Registered serial $serial as role: $role')
print(f'Saved to {f}')
"
}

# --- Main ---
case "${1:-}" in
    --help|-h)
        echo "Usage: $0 [SERIAL ROLE]"
        echo "  No args: detect all connected RP2040 boards"
        echo "  SERIAL ROLE: register a board (e.g. $0 E0C9125B0D9B tx)"
        echo ""
        echo "Known serials:"
        cat "$KNOWN_SERIALS_FILE" 2>/dev/null || echo "  (none registered yet)"
        ;;
    "")
        detect_picos
        echo ""
        generate_rules
        ;;
    *)
        if [ -z "${2:-}" ]; then
            echo "Error: need both SERIAL and ROLE (tx/rx)"
            exit 1
        fi
        register_serial "$1" "$2"
        generate_rules
        ;;
esac
